server:
  port: 8000
  servlet:
    context-path: /api

spring:
  application:
    name: bc-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_care
    username: postgres
    password: 123456Aa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc.time_zone: UTC+07:00
    database: postgresql
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect