server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bc-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:6002/booking_care
    username: booking_care
    password: booking_care
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: trace


application:
  jwt:
    access-token-secret-key: 95666c8f96c9e6a6b235aca16840495e7c722b2f333f89eb8d3f21b9517e6bbd
    access-token-expiration-ms: 7200000
    refresh-token-secret-key: c9e021ede5c0080a52be14666fc224a0f09bb376ddbfff1e91323a00838a9bbe
    refresh-token-expiration-ms: 2592000000
    reset-password-token-secret-key: b17970f589b5d63f0c84dfd711f5cdd96d42af86bab4bc75fc3651b1b52e8ed9
    reset-password-token-expiration-ms: 300000